SET SQL_SAFE_UPDATES = 0;

DROP DATABASE IF EXISTS burgers_db;

CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE  burgers  (
 id INT NOT NULL AUTO_INCREMENT,
 burger_name VARCHAR(100) NULL,
 devoured BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id)
  );